import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
    paddingHorizontal: 28,
  },
  contentContainer: {
    flexGrow: 1,
    paddingVertical: 20,
  },
  backButton: {
    marginTop: 10,
    marginBottom: 20,
    alignSelf: "flex-start",
  },
  title: {
    fontSize: 24,
    fontWeight: "500",
    color: "#120D26",
    marginBottom: 24,
  },
  inputWrapper: {
    marginBottom: 16,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E4DFDF",
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 56,
    backgroundColor: "#FFFFFF",
  },
  input: {
    flex: 1,
    fontSize: 14,
    color: "#120D26",
  },
  inputIcon: {
    width: 24,
    height: 24,
    marginRight: 10,
    tintColor: "#747688",
  },
  signUpButton: {
    backgroundColor: "#5669FF",
    height: 58,
    borderRadius: 15,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    shadowColor: "#5669FF",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
    marginTop: 15,
    width: "80%",
    alignSelf: "center",
  },
  signUpButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  arrowCircle: {
    position: "absolute",
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#3D56F0",
    justifyContent: "center",
    alignItems: "center",
  },
  orText: {
    textAlign: "center",
    color: "#9D9898",
    fontSize: 16,
    fontWeight: "400",
    marginVertical: 20,
  },
  socialButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E4DFDF",
    borderRadius: 12,
    height: 56,
    marginBottom: 16,
    backgroundColor: "#FFFFFF",
    width: "80%",
    alignSelf: "center",
  },
  socialIcon: {
    width: 22,
    height: 22,
    marginRight: 10,
  },
  socialButtonText: {
    fontSize: 14,
    color: "#120D26",
    fontWeight: "400",
  },
  footerContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 15,
    marginBottom: 30,
  },
  footerText: {
    fontSize: 14,
    color: "#120D26",
  },
  signInText: {
    fontSize: 14,
    color: "#5669FF",
    fontWeight: "300",
  },
});

export default styles;